"""DuckDB schema for critical SBER predictive data."""

DDL = """
CREATE TABLE IF NOT EXISTS historical_equity_universe(secid VARCHAR PRIMARY KEY,name VARCHAR,isin VARCHAR,regnumber VARCHAR,instrument_type VARCHAR,group_id VARCHAR,primary_board VARCHAR,is_traded BOOLEAN,first_trade DATE,last_trade DATE,sector VARCHAR,industry VARCHAR,termination_reason VARCHAR,source VARCHAR,discovered_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS historical_security_lifecycles(secid VARCHAR,board VARCHAR,history_from DATE,history_to DATE,is_primary BOOLEAN,is_traded BOOLEAN,technical_mode BOOLEAN,source VARCHAR,PRIMARY KEY(secid,board));
CREATE TABLE IF NOT EXISTS historical_security_identifiers(secid VARCHAR,identifier_type VARCHAR,identifier_value VARCHAR,valid_from DATE,valid_to DATE,related_secid VARCHAR,relation_type VARCHAR,source VARCHAR,PRIMARY KEY(secid,identifier_type,identifier_value));
CREATE TABLE IF NOT EXISTS historical_universe_membership(trade_date DATE,secid VARCHAR,board VARCHAR,universe_kind VARCHAR,is_ordinary_share BOOLEAN,valid_price BOOLEAN,past_liquidity DOUBLE,eligible BOOLEAN,available_from TIMESTAMPTZ,PRIMARY KEY(trade_date,secid,universe_kind));
CREATE TABLE IF NOT EXISTS critical_breadth(trade_date DATE,universe_kind VARCHAR,universe_size INTEGER,advancing INTEGER,declining INTEGER,equal_return DOUBLE,liquidity_return DOUBLE,above_sma20 DOUBLE,above_sma50 DOUBLE,above_sma200 DOUBLE,dispersion DOUBLE,volatility DOUBLE,momentum DOUBLE,PRIMARY KEY(trade_date,universe_kind));
CREATE TABLE IF NOT EXISTS zcyc_observations(observation_date DATE,publication_date DATE,available_from TIMESTAMPTZ,tenor DOUBLE,zero_coupon_yield DOUBLE,parameters_json JSON,source VARCHAR,revision_id VARCHAR,loaded_at TIMESTAMP,PRIMARY KEY(observation_date,tenor,revision_id));
CREATE TABLE IF NOT EXISTS zcyc_features(observation_date DATE,available_from TIMESTAMPTZ,short_rate DOUBLE,long_rate DOUBLE,slope_10y_2y DOUBLE,slope_10y_1y DOUBLE,slope_5y_1y DOUBLE,curvature DOUBLE,parallel_shift DOUBLE,steepening DOUBLE,flattening BOOLEAN,inversion BOOLEAN,rolling_volatility DOUBLE,forward_proxy DOUBLE,rate_regime VARCHAR,PRIMARY KEY(observation_date));
CREATE TABLE IF NOT EXISTS sber_futures_contracts(secid VARCHAR PRIMARY KEY,asset_code VARCHAR,shortname VARCHAR,first_trade DATE,last_trade DATE,expiration DATE,step_price DOUBLE,specification_version VARCHAR,source VARCHAR);
CREATE TABLE IF NOT EXISTS sber_futures_daily(trade_date DATE,secid VARCHAR,open DOUBLE,high DOUBLE,low DOUBLE,close DOUBLE,settle DOUBLE,volume DOUBLE,open_interest DOUBLE,num_trades BIGINT,source VARCHAR,available_from TIMESTAMPTZ,PRIMARY KEY(trade_date,secid));
CREATE TABLE IF NOT EXISTS sber_futures_rolls(rule VARCHAR,roll_date DATE,old_contract VARCHAR,new_contract VARCHAR,reason VARCHAR,price_difference DOUBLE,adjustment DOUBLE,old_volume DOUBLE,new_volume DOUBLE,old_oi DOUBLE,new_oi DOUBLE,PRIMARY KEY(rule,roll_date));
CREATE TABLE IF NOT EXISTS sber_continuous_futures(trade_date DATE,rule VARCHAR,source_contract VARCHAR,front_contract VARCHAR,next_contract VARCHAR,raw_close DOUBLE,back_adjusted_close DOUBLE,ratio_adjusted_close DOUBLE,spot_close DOUBLE,basis DOUBLE,annualized_basis DOUBLE,open_interest DOUBLE,oi_change DOUBLE,volume DOUBLE,volume_change DOUBLE,PRIMARY KEY(trade_date,rule));
CREATE TABLE IF NOT EXISTS sber_ifrs_discovery(document_id VARCHAR PRIMARY KEY,title VARCHAR,publication_date DATE,period_end DATE,period_type VARCHAR,audit_status VARCHAR,format VARCHAR,url VARCHAR,file_hash VARCHAR,processing_status VARCHAR,technical_result VARCHAR,source VARCHAR,checked_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS sber_ifrs_review(document_id VARCHAR,metric VARCHAR,source_page VARCHAR,source_table VARCHAR,source_row VARCHAR,unit VARCHAR,candidate_value DOUBLE,review_reason VARCHAR,status VARCHAR,PRIMARY KEY(document_id,metric));
CREATE TABLE IF NOT EXISTS moex_options_audit(secid VARCHAR PRIMARY KEY,underlying VARCHAR,strike DOUBLE,option_type VARCHAR,expiration DATE,first_trade DATE,last_trade DATE,volume DOUBLE,open_interest DOUBLE,settlement DOUBLE,bid DOUBLE,ask DOUBLE,theoretical_price DOUBLE,implied_volatility DOUBLE,history_accessible BOOLEAN,quality_status VARCHAR,source VARCHAR,checked_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS intraday_candles(secid VARCHAR,interval_minutes INTEGER,begin TIMESTAMPTZ,end_at TIMESTAMPTZ,open DOUBLE,high DOUBLE,low DOUBLE,close DOUBLE,volume DOUBLE,value DOUBLE,session VARCHAR,source VARCHAR,PRIMARY KEY(secid,interval_minutes,begin));
CREATE TABLE IF NOT EXISTS intraday_features(secid VARCHAR,trade_date DATE,overnight_gap DOUBLE,opening_return DOUBLE,main_return DOUBLE,evening_return DOUBLE,realized_volatility DOUBLE,vwap_deviation DOUBLE,first_hour_momentum DOUBLE,last_hour_momentum DOUBLE,intraday_reversal DOUBLE,PRIMARY KEY(secid,trade_date));
CREATE TABLE IF NOT EXISTS critical_source_catalog(dataset_id VARCHAR PRIMARY KEY,source VARCHAR,endpoint VARCHAR,found BOOLEAN,accessible BOOLEAN,downloaded BOOLEAN,parsed BOOLEAN,validated BOOLEAN,rows_count BIGINT,date_from DATE,date_to DATE,pit_status VARCHAR,quality VARCHAR,production_eligibility VARCHAR,rejection_reason VARCHAR,cost_status VARCHAR,next_operation VARCHAR,checked_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS critical_quality_issues(issue_id VARCHAR PRIMARY KEY,dataset_id VARCHAR,issue_type VARCHAR,severity VARCHAR,details VARCHAR,detected_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS critical_data_readiness(block_id VARCHAR PRIMARY KEY,status VARCHAR,rows_count BIGINT,date_from DATE,date_to DATE,evidence VARCHAR,updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS critical_ablation_results(horizon INTEGER,block_name VARCHAR,common_sample_size INTEGER,effective_sample_size DOUBLE,baseline_score DOUBLE,block_score DOUBLE,improvement DOUBLE,ci_low DOUBLE,ci_high DOUBLE,folds_won INTEGER,status VARCHAR,details_json JSON,run_hash VARCHAR,PRIMARY KEY(horizon,block_name,run_hash));
"""
