"""Official source catalogue."""

SOURCES = [
    {
        "source_id": "sber_ir",
        "name": "Sber Investor Relations",
        "domain": "sberbank.com",
        "source_type": "issuer",
        "trust": 1.0,
        "timezone": "Europe/Moscow",
        "archive": True,
        "method": "HTML/PDF discovery",
        "limitations": "archive layout may change",
        "license": "metadata and links only",
    },
    {
        "source_id": "cbr",
        "name": "Bank of Russia",
        "domain": "cbr.ru",
        "source_type": "regulator",
        "trust": 1.0,
        "timezone": "Europe/Moscow",
        "archive": True,
        "method": "official HTML/API",
        "limitations": "publication time may be date-only",
        "license": "official open data",
    },
    {
        "source_id": "moex",
        "name": "Moscow Exchange ISS",
        "domain": "iss.moex.com",
        "source_type": "exchange",
        "trust": 1.0,
        "timezone": "Europe/Moscow",
        "archive": True,
        "method": "ISS JSON",
        "limitations": "some corporate dates absent",
        "license": "ISS terms",
    },
    {
        "source_id": "disclosure",
        "name": "Interfax Disclosure Centre",
        "domain": "e-disclosure.ru",
        "source_type": "disclosure",
        "trust": 0.95,
        "timezone": "Europe/Moscow",
        "archive": True,
        "method": "metadata discovery",
        "limitations": "availability and throttling",
        "license": "links and metadata only",
    },
    {
        "source_id": "government",
        "name": "Government of Russia",
        "domain": "government.ru",
        "source_type": "government",
        "trust": 1.0,
        "timezone": "Europe/Moscow",
        "archive": True,
        "method": "official pages",
        "limitations": "only directly relevant items",
        "license": "official publication",
    },
    {
        "source_id": "minfin",
        "name": "Ministry of Finance",
        "domain": "minfin.gov.ru",
        "source_type": "government",
        "trust": 1.0,
        "timezone": "Europe/Moscow",
        "archive": True,
        "method": "official pages",
        "limitations": "only directly relevant items",
        "license": "official publication",
    },
]
