"""DuckDB schema for the predictive-data foundation."""

DDL = """
CREATE TABLE IF NOT EXISTS predictive_data_catalog(dataset_id VARCHAR,category VARCHAR,series_id VARCHAR,name VARCHAR,economic_meaning VARCHAR,source VARCHAR,endpoint VARCHAR,instrument VARCHAR,frequency VARCHAR,timezone VARCHAR,available_history_from DATE,available_history_to DATE,publication_delay VARCHAR,available_from_rule VARCHAR,revisions_possible BOOLEAN,license_status VARCHAR,point_in_time_status VARCHAR,ingestion_status VARCHAR,model_eligibility VARCHAR,limitations VARCHAR,last_checked_at TIMESTAMP,PRIMARY KEY(dataset_id,series_id));
CREATE TABLE IF NOT EXISTS predictive_market_universe(canonical_secid VARCHAR,source_secid VARCHAR,board VARCHAR,sector VARCHAR,industry VARCHAR,active_from DATE,active_to DATE,is_traded BOOLEAN,liquidity_value DOUBLE,capitalization DOUBLE,survivorship_status VARCHAR,source VARCHAR,available_from TIMESTAMPTZ,PRIMARY KEY(source_secid,board));
CREATE TABLE IF NOT EXISTS predictive_market_prices(trade_date DATE,secid VARCHAR,board VARCHAR,open DOUBLE,high DOUBLE,low DOUBLE,close DOUBLE,volume DOUBLE,value DOUBLE,num_trades BIGINT,available_from TIMESTAMPTZ,source VARCHAR,PRIMARY KEY(trade_date,secid,board));
CREATE TABLE IF NOT EXISTS predictive_index_membership(index_id VARCHAR,effective_from DATE,effective_to DATE,constituent VARCHAR,weight DOUBLE,free_float DOUBLE,source VARCHAR,publication_date DATE,available_from TIMESTAMPTZ,status VARCHAR,PRIMARY KEY(index_id,effective_from,constituent));
CREATE TABLE IF NOT EXISTS predictive_market_breadth(trade_date DATE,universe_size INTEGER,advancing INTEGER,declining INTEGER,advance_decline_ratio DOUBLE,advance_decline_line DOUBLE,above_sma20 DOUBLE,above_sma50 DOUBLE,above_sma200 DOUBLE,new_high_20 INTEGER,new_low_20 INTEGER,new_high_60 INTEGER,new_low_60 INTEGER,new_high_250 INTEGER,new_low_250 INTEGER,median_return DOUBLE,equal_weight_return DOUBLE,cap_weight_return DOUBLE,cross_sectional_volatility DOUBLE,strong_drawdown_share DOUBLE,financial_breadth DOUBLE,calculation_version VARCHAR,calculated_at TIMESTAMP,PRIMARY KEY(trade_date,calculation_version));
CREATE TABLE IF NOT EXISTS sber_relative_market_state(trade_date DATE,sber_return DOUBLE,imoex_return DOUBLE,finance_return DOUBLE,equal_market_return DOUBLE,sber_vs_imoex DOUBLE,sber_vs_finance DOUBLE,sber_vs_equal DOUBLE,relative_momentum_20 DOUBLE,relative_volatility_60 DOUBLE,rolling_beta_60 DOUBLE,rolling_alpha_60 DOUBLE,residual_return DOUBLE,idiosyncratic_volatility_60 DOUBLE,calculation_version VARCHAR,PRIMARY KEY(trade_date,calculation_version));
CREATE TABLE IF NOT EXISTS predictive_derivative_instruments(secid VARCHAR PRIMARY KEY,shortname VARCHAR,asset_code VARCHAR,instrument_type VARCHAR,expiration_date DATE,underlying VARCHAR,board VARCHAR,is_traded BOOLEAN,source VARCHAR,last_checked_at TIMESTAMP,model_eligibility VARCHAR,limitations VARCHAR);
CREATE TABLE IF NOT EXISTS predictive_derivative_daily(trade_date DATE,secid VARCHAR,contract_role VARCHAR,settle_price DOUBLE,close DOUBLE,volume DOUBLE,open_interest DOUBLE,days_to_expiry INTEGER,spot_price DOUBLE,basis DOUBLE,annualized_basis DOUBLE,source VARCHAR,available_from TIMESTAMPTZ,PRIMARY KEY(trade_date,secid));
CREATE TABLE IF NOT EXISTS predictive_yield_curve(observation_date DATE,tenor_years DOUBLE,yield_value DOUBLE,publication_date DATE,available_from TIMESTAMPTZ,source VARCHAR,revision_id VARCHAR,PRIMARY KEY(observation_date,tenor_years,revision_id));
CREATE TABLE IF NOT EXISTS predictive_feature_families(family_id VARCHAR PRIMARY KEY,raw_series_json JSON,transformations_json JSON,economic_interpretation VARCHAR,available_horizons_json JSON,pit_status VARCHAR,missingness DOUBLE,stability VARCHAR,expected_sign_hypothesis VARCHAR,production_eligibility VARCHAR,updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS structural_regimes(regime_id VARCHAR PRIMARY KEY,effective_from DATE,effective_to DATE,regime VARCHAR,evidence_json JSON,detected_from_data BOOLEAN,comparability_status VARCHAR,calculation_version VARCHAR);
CREATE TABLE IF NOT EXISTS predictive_coverage_audit(dataset_id VARCHAR,series_id VARCHAR,date_from DATE,date_to DATE,observations BIGINT,frequency VARCHAR,missingness DOUBLE,stale_periods INTEGER,publication_lag VARCHAR,structural_breaks_json JSON,extreme_values INTEGER,revisions INTEGER,timezone VARCHAR,pit_status VARCHAR,usable_horizons_json JSON,audited_at TIMESTAMP,PRIMARY KEY(dataset_id,series_id));
CREATE TABLE IF NOT EXISTS predictive_ablation_results(horizon INTEGER,block_name VARCHAR,sample_start DATE,sample_end DATE,common_sample_size INTEGER,effective_sample_size DOUBLE,baseline_score DOUBLE,block_score DOUBLE,improvement DOUBLE,holdout_improvement DOUBLE,bootstrap_low DOUBLE,bootstrap_high DOUBLE,status VARCHAR,details_json JSON,calculation_version VARCHAR,PRIMARY KEY(horizon,block_name,calculation_version));
CREATE TABLE IF NOT EXISTS predictive_lead_lag(pair_id VARCHAR,lag INTEGER,correlation DOUBLE,sample_size INTEGER,interpretation VARCHAR,calculation_version VARCHAR,PRIMARY KEY(pair_id,lag,calculation_version));
"""
