"""DuckDB schema for SBER deep historical backfill."""

DDL = """
CREATE TABLE IF NOT EXISTS deep_zcyc_archive(observation_date DATE,publication_date DATE,available_from TIMESTAMPTZ,tenor DOUBLE,zero_coupon_yield DOUBLE,parameters_json JSON,source VARCHAR,parser_version VARCHAR,revision_id VARCHAR,quality_status VARCHAR,loaded_at TIMESTAMP,PRIMARY KEY(observation_date,tenor,revision_id));
CREATE TABLE IF NOT EXISTS expired_sber_futures(secid VARCHAR PRIMARY KEY,shortname VARCHAR,first_trade DATE,last_trade DATE,expiration DATE,is_traded BOOLEAN,asset_code VARCHAR,multiplier DOUBLE,tick_size DOUBLE,price_scale DOUBLE,underlying_units DOUBLE,specification_status VARCHAR,source VARCHAR,discovered_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS deep_sber_futures_daily(trade_date DATE,secid VARCHAR,open DOUBLE,high DOUBLE,low DOUBLE,close DOUBLE,settlement DOUBLE,volume DOUBLE,value DOUBLE,open_interest DOUBLE,num_trades BIGINT,available_from TIMESTAMPTZ,source VARCHAR,PRIMARY KEY(trade_date,secid));
CREATE TABLE IF NOT EXISTS deep_futures_rolls(rule VARCHAR,roll_date DATE,old_contract VARCHAR,new_contract VARCHAR,reason VARCHAR,old_price DOUBLE,new_price DOUBLE,price_difference DOUBLE,ratio DOUBLE,old_volume DOUBLE,new_volume DOUBLE,old_oi DOUBLE,new_oi DOUBLE,pit_safe BOOLEAN,PRIMARY KEY(rule,roll_date));
CREATE TABLE IF NOT EXISTS deep_continuous_futures(trade_date DATE,rule VARCHAR,source_contract VARCHAR,front_contract VARCHAR,next_contract VARCHAR,raw_close DOUBLE,back_adjusted_close DOUBLE,ratio_adjusted_close DOUBLE,settlement DOUBLE,volume DOUBLE,open_interest DOUBLE,basis DOUBLE,annualized_basis DOUBLE,basis_status VARCHAR,PRIMARY KEY(trade_date,rule));
CREATE TABLE IF NOT EXISTS dynamic_liquid_universe(trade_date DATE,secid VARCHAR,board VARCHAR,trailing_turnover DOUBLE,trailing_trade_days INTEGER,rank INTEGER,is_ordinary_share BOOLEAN,is_special_mode BOOLEAN,eligible BOOLEAN,selection_version VARCHAR,available_from TIMESTAMPTZ,PRIMARY KEY(trade_date,secid,selection_version));
CREATE TABLE IF NOT EXISTS survivorship_impact_daily(trade_date DATE,current40_breadth DOUBLE,dynamic_breadth DOUBLE,difference DOUBLE,current40_return DOUBLE,dynamic_return DOUBLE,return_difference DOUBLE,current40_size INTEGER,dynamic_size INTEGER,calculation_version VARCHAR,PRIMARY KEY(trade_date,calculation_version));
CREATE TABLE IF NOT EXISTS historical_financial_sector(trade_date DATE,secid VARCHAR,subsector VARCHAR,official_metadata_available BOOLEAN,equal_return DOUBLE,liquidity_return DOUBLE,breadth DOUBLE,momentum DOUBLE,volatility DOUBLE,dispersion DOUBLE,sber_residual DOUBLE,sber_relative_strength DOUBLE,sector_beta DOUBLE,idiosyncratic_return DOUBLE,source VARCHAR,PRIMARY KEY(trade_date,secid));
CREATE TABLE IF NOT EXISTS deep_intraday_coverage(secid VARCHAR,interval_minutes INTEGER,date_from TIMESTAMPTZ,date_to TIMESTAMPTZ,rows_count BIGINT,sessions_json JSON,history_kind VARCHAR,source VARCHAR,quality_status VARCHAR,PRIMARY KEY(secid,interval_minutes));
CREATE TABLE IF NOT EXISTS ifrs_review_validation(document_id VARCHAR,metric VARCHAR,source_page VARCHAR,source_table VARCHAR,source_line VARCHAR,raw_text_fragment VARCHAR,candidate_value DOUBLE,unit VARCHAR,confidence DOUBLE,validation_status VARCHAR,rejection_reason VARCHAR,reviewed_at TIMESTAMP,PRIMARY KEY(document_id,metric));
CREATE TABLE IF NOT EXISTS options_history_coverage(secid VARCHAR PRIMARY KEY,underlying VARCHAR,expiration DATE,history_rows BIGINT,date_from DATE,date_to DATE,snapshot_rows BIGINT,history_accessible BOOLEAN,history_endpoint VARCHAR,access_result VARCHAR,quality_status VARCHAR,checked_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS sber_predictive_common_sample(trade_date DATE,forecast_cutoff TIMESTAMPTZ,horizon INTEGER,target_available BOOLEAN,technical_available BOOLEAN,historical_breadth_available BOOLEAN,financial_sector_available BOOLEAN,zcyc_available BOOLEAN,futures_available BOOLEAN,intraday_available BOOLEAN,ifrs_available BOOLEAN,options_available BOOLEAN,feature_counts_json JSON,feature_age_json JSON,missingness_json JSON,pit_status_json JSON,quality_status_json JSON,feature_version VARCHAR,target_version VARCHAR,PRIMARY KEY(trade_date,horizon,feature_version,target_version));
CREATE TABLE IF NOT EXISTS sber_coverage_tiers(horizon INTEGER,tier INTEGER,date_from DATE,date_to DATE,rows_count BIGINT,effective_sample_size DOUBLE,folds INTEGER,available_blocks_json JSON,suitability VARCHAR,calculation_version VARCHAR,PRIMARY KEY(horizon,tier,calculation_version));
CREATE TABLE IF NOT EXISTS deep_ablation_results(horizon INTEGER,comparison VARCHAR,tier INTEGER,common_rows BIGINT,effective_sample_size DOUBLE,folds INTEGER,balanced_accuracy DOUBLE,roc_auc DOUBLE,brier DOUBLE,log_loss DOUBLE,mae DOUBLE,rmse DOUBLE,sign_accuracy DOUBLE,correlation DOUBLE,rank_correlation DOUBLE,ci_low DOUBLE,ci_high DOUBLE,status VARCHAR,run_hash VARCHAR,details_json JSON,PRIMARY KEY(horizon,comparison,run_hash));
CREATE TABLE IF NOT EXISTS sber_model_readiness(horizon INTEGER PRIMARY KEY,status VARCHAR,common_rows BIGINT,effective_sample_size DOUBLE,folds INTEGER,highest_tier INTEGER,available_blocks_json JSON,blocking_reasons_json JSON,updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS deep_backfill_audit(dataset_id VARCHAR PRIMARY KEY,endpoint VARCHAR,rows_count BIGINT,date_from DATE,date_to DATE,found BOOLEAN,accessible BOOLEAN,downloaded BOOLEAN,parsed BOOLEAN,validated BOOLEAN,pit_status VARCHAR,quality_status VARCHAR,cost_status VARCHAR,evidence VARCHAR,next_operation VARCHAR,checked_at TIMESTAMP);
"""
