"""Schema for instrument-agnostic portfolio research."""

DDL = """
CREATE TABLE IF NOT EXISTS portfolio_instruments(secid VARCHAR PRIMARY KEY,isin VARCHAR,name VARCHAR,issuer VARCHAR,share_class VARCHAR,security_type VARCHAR,primary_board VARCHAR,lot_size DOUBLE,sector VARCHAR,industry VARCHAR,listing_level INTEGER,currency VARCHAR,start_date DATE,end_date DATE,dividend_policy_type VARCHAR,fundamental_model_family VARCHAR,available_derivatives_json JSON,source_coverage_json JSON,analysis_status VARCHAR,verified_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS instrument_identities(canonical_secid VARCHAR,source_secid VARCHAR,isin VARCHAR,registration_number VARCHAR,legal_successor VARCHAR,conversion_ratio DOUBLE,valid_from DATE,valid_to DATE,identity_status VARCHAR,evidence_source VARCHAR,PRIMARY KEY(canonical_secid,source_secid,valid_from));
CREATE TABLE IF NOT EXISTS instrument_lifecycles(canonical_secid VARCHAR,event_date DATE,event_type VARCHAR,old_value VARCHAR,new_value VARCHAR,conversion_ratio DOUBLE,legal_continuity VARCHAR,source VARCHAR,validation_status VARCHAR,notes VARCHAR,PRIMARY KEY(canonical_secid,event_date,event_type));
CREATE TABLE IF NOT EXISTS instrument_analysis_profiles(secid VARCHAR PRIMARY KEY,fundamental_family VARCHAR,preferred_pair VARCHAR,benchmark VARCHAR,sector_benchmark VARCHAR,allowed_horizons_json JSON,research_only BOOLEAN,no_trade_recommendation BOOLEAN,profile_version VARCHAR);
CREATE TABLE IF NOT EXISTS instrument_source_availability(secid VARCHAR,source_type VARCHAR,status VARCHAR,date_from DATE,date_to DATE,rows_count BIGINT,source VARCHAR,freshness_status VARCHAR,quality_status VARCHAR,notes VARCHAR,updated_at TIMESTAMP,PRIMARY KEY(secid,source_type));
CREATE TABLE IF NOT EXISTS instrument_model_versions(secid VARCHAR,model_type VARCHAR,version VARCHAR,status VARCHAR,trained_from DATE,trained_to DATE,methodology VARCHAR,input_hash VARCHAR,created_at TIMESTAMP,PRIMARY KEY(secid,model_type,version));
CREATE TABLE IF NOT EXISTS external_project_audit(project_id VARCHAR PRIMARY KEY,name VARCHAR,repository_url VARCHAR,owner VARCHAR,license VARCHAR,license_file_hash VARCHAR,last_commit_date TIMESTAMP,latest_release VARCHAR,activity_status VARCHAR,language VARCHAR,dependencies JSON,supported_markets JSON,data_sources JSON,implemented_features JSON,test_coverage_status VARCHAR,architectural_value VARCHAR,methodological_value VARCHAR,legal_reuse_status VARCHAR,security_risk VARCHAR,integration_recommendation VARCHAR,audit_notes VARCHAR,audited_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS portfolio_cross_instrument_factors(run_id VARCHAR,feature VARCHAR,horizon INTEGER,instruments_working INTEGER,sectors_working INTEGER,sign_consistency DOUBLE,mean_ic DOUBLE,min_ic DOUBLE,max_ic DOUBLE,status VARCHAR,details_json JSON,PRIMARY KEY(run_id,feature,horizon));
CREATE TABLE IF NOT EXISTS instrument_alpha_results(run_id VARCHAR,secid VARCHAR,horizon INTEGER,feature VARCHAR,ic DOUBLE,rank_ic DOUBLE,p_value DOUBLE,ci_low DOUBLE,ci_high DOUBLE,folds_positive INTEGER,folds INTEGER,stability_score DOUBLE,regime_dependence VARCHAR,status VARCHAR,PRIMARY KEY(run_id,secid,horizon,feature));
CREATE TABLE IF NOT EXISTS preferred_share_rules(preferred_secid VARCHAR PRIMARY KEY,ordinary_secid VARCHAR,dividend_rights VARCHAR,formula VARCHAR,liquidity_status VARCHAR,corporate_rights VARCHAR,policy_change_risk VARCHAR,source VARCHAR,validation_status VARCHAR,updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS preferred_share_spreads(trade_date DATE,preferred_secid VARCHAR,ordinary_secid VARCHAR,preferred_close DOUBLE,ordinary_close DOUBLE,discount_premium DOUBLE,relative_momentum DOUBLE,relative_drawdown DOUBLE,PRIMARY KEY(trade_date,preferred_secid));
CREATE TABLE IF NOT EXISTS portfolio_snapshots(snapshot_id VARCHAR PRIMARY KEY,as_of_date DATE,created_at TIMESTAMP,positions_hash VARCHAR,total_value DOUBLE,cash DOUBLE,status VARCHAR);
CREATE TABLE IF NOT EXISTS portfolio_positions(snapshot_id VARCHAR,secid VARCHAR,quantity DOUBLE,average_price DOUBLE,current_price DOUBLE,market_value DOUBLE,weight DOUBLE,target_weight DOUBLE,max_weight DOUBLE,can_add BOOLEAN,horizon INTEGER,PRIMARY KEY(snapshot_id,secid));
CREATE TABLE IF NOT EXISTS portfolio_returns(snapshot_id VARCHAR,trade_date DATE,total_return DOUBLE,index_value DOUBLE,PRIMARY KEY(snapshot_id,trade_date));
CREATE TABLE IF NOT EXISTS portfolio_risk_metrics(snapshot_id VARCHAR,metric VARCHAR,value DOUBLE,method VARCHAR,confidence VARCHAR,details_json JSON,PRIMARY KEY(snapshot_id,metric));
CREATE TABLE IF NOT EXISTS portfolio_factor_exposures(snapshot_id VARCHAR,factor VARCHAR,exposure DOUBLE,method VARCHAR,confidence VARCHAR,PRIMARY KEY(snapshot_id,factor));
CREATE TABLE IF NOT EXISTS portfolio_sector_exposures(snapshot_id VARCHAR,sector VARCHAR,weight DOUBLE,PRIMARY KEY(snapshot_id,sector));
CREATE TABLE IF NOT EXISTS portfolio_dividend_forecasts(snapshot_id VARCHAR,secid VARCHAR,scenario VARCHAR,expected_cash DOUBLE,confidence VARCHAR,source VARCHAR,PRIMARY KEY(snapshot_id,secid,scenario));
CREATE TABLE IF NOT EXISTS portfolio_concentration(snapshot_id VARCHAR,dimension VARCHAR,name VARCHAR,weight DOUBLE,limit_value DOUBLE,status VARCHAR,PRIMARY KEY(snapshot_id,dimension,name));
CREATE TABLE IF NOT EXISTS portfolio_scenarios(snapshot_id VARCHAR,scenario VARCHAR,estimated_change DOUBLE,confidence VARCHAR,method VARCHAR,winners_json JSON,losers_json JSON,PRIMARY KEY(snapshot_id,scenario));
CREATE TABLE IF NOT EXISTS portfolio_rebalancing_experiments(snapshot_id VARCHAR,method VARCHAR,weights_json JSON,expected_volatility DOUBLE,diversification_ratio DOUBLE,turnover DOUBLE,transaction_cost DOUBLE,constraints_status VARCHAR,research_only BOOLEAN,PRIMARY KEY(snapshot_id,method));
CREATE TABLE IF NOT EXISTS portfolio_dividend_calendar(secid VARCHAR,scenario VARCHAR,recommendation_date DATE,approval_date DATE,record_date DATE,payment_date DATE,dps DOUBLE,currency VARCHAR,confidence VARCHAR,source VARCHAR,PRIMARY KEY(secid,scenario,record_date));
CREATE TABLE IF NOT EXISTS portfolio_live_shadow(shadow_id VARCHAR PRIMARY KEY,created_at TIMESTAMP,as_of_date DATE,secid VARCHAR,price DOUBLE,regime VARCHAR,research_candidates_json JSON,qualitative_direction VARCHAR,range_fallback_json JSON,risk_state_json JSON,dividend_state_json JSON,data_confidence VARCHAR,model_version VARCHAR,input_hash VARCHAR,immutable BOOLEAN,status VARCHAR);
CREATE TABLE IF NOT EXISTS portfolio_pipeline_runs(run_id VARCHAR PRIMARY KEY,started_at TIMESTAMP,finished_at TIMESTAMP,status VARCHAR,steps_json JSON,rows_written BIGINT,no_change BOOLEAN,version VARCHAR);
CREATE TABLE IF NOT EXISTS portfolio_alpha_validations(run_id VARCHAR,secid VARCHAR,feature VARCHAR,horizon INTEGER,status VARCHAR,n BIGINT,effective_n DOUBLE,oos_ic DOUBLE,oos_rank_ic DOUBLE,baseline_mse DOUBLE,model_mse DOUBLE,momentum_mse DOUBLE,hac_t DOUBLE,ci_low DOUBLE,ci_high DOUBLE,folds_stable INTEGER,folds INTEGER,regime_json JSON,sanity_json JSON,methodology_version VARCHAR,PRIMARY KEY(run_id,secid,feature,horizon));
CREATE TABLE IF NOT EXISTS portfolio_alpha_fold_predictions(run_id VARCHAR,secid VARCHAR,feature VARCHAR,horizon INTEGER,fold INTEGER,trade_date DATE,actual DOUBLE,prediction DOUBLE,baseline DOUBLE,momentum DOUBLE,coefficient DOUBLE,regime VARCHAR,PRIMARY KEY(run_id,secid,feature,horizon,trade_date));
CREATE TABLE IF NOT EXISTS portfolio_alpha_bootstrap(run_id VARCHAR,secid VARCHAR,feature VARCHAR,horizon INTEGER,draw INTEGER,delta_mse DOUBLE,ic DOUBLE,PRIMARY KEY(run_id,secid,feature,horizon,draw));
CREATE TABLE IF NOT EXISTS portfolio_cross_validations(run_id VARCHAR,feature VARCHAR,horizon INTEGER,held_out_secid VARCHAR,train_sign DOUBLE,test_ic DOUBLE,test_rank_ic DOUBLE,n BIGINT,effective_n DOUBLE,class VARCHAR,status VARCHAR,PRIMARY KEY(run_id,feature,horizon,held_out_secid));
CREATE TABLE IF NOT EXISTS portfolio_metric_reconciliation(run_id VARCHAR,metric VARCHAR,native_value DOUBLE,external_value DOUBLE,absolute_difference DOUBLE,tolerance DOUBLE,status VARCHAR,formula_native VARCHAR,formula_external VARCHAR,reason VARCHAR,PRIMARY KEY(run_id,metric));
CREATE TABLE IF NOT EXISTS external_method_audits(project VARCHAR PRIMARY KEY,version VARCHAR,license VARCHAR,isolated_command VARCHAR,test_result VARCHAR,decision VARCHAR,notes VARCHAR,audited_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS issuer_source_maps(secid VARCHAR,adapter VARCHAR,metric VARCHAR,reporting_standard VARCHAR,source VARCHAR,source_type VARCHAR,publication_date_rule VARCHAR,available_from_rule VARCHAR,status VARCHAR,notes VARCHAR,PRIMARY KEY(secid,metric,reporting_standard));
CREATE TABLE IF NOT EXISTS portfolio_dividend_outlook(snapshot_id VARCHAR,secid VARCHAR,scenario VARCHAR,month DATE,gross DOUBLE,estimated_tax DOUBLE,net DOUBLE,dps DOUBLE,yield_current DOUBLE,yield_cost DOUBLE,status VARCHAR,confidence VARCHAR,PRIMARY KEY(snapshot_id,secid,scenario,month));
CREATE TABLE IF NOT EXISTS portfolio_scenarios_v2(snapshot_id VARCHAR,secid VARCHAR,scenario VARCHAR,mechanical_sensitivity DOUBLE,range_low DOUBLE,range_high DOUBLE,confidence VARCHAR,method VARCHAR,structural_break_warning BOOLEAN,PRIMARY KEY(snapshot_id,secid,scenario));
CREATE TABLE IF NOT EXISTS real_portfolio_live_shadow(snapshot_id VARCHAR PRIMARY KEY,created_at TIMESTAMP,as_of_date DATE,mode VARCHAR,portfolio_value DOUBLE,weights_json JSON,risk_json JSON,factors_json JSON,dividend_json JSON,regime VARCHAR,variants_json JSON,input_hash VARCHAR,model_versions_json JSON,immutable BOOLEAN);
CREATE TABLE IF NOT EXISTS backtest_reconciliation(backend VARCHAR,test_case VARCHAR,native_value DOUBLE,external_value DOUBLE,tolerance DOUBLE,status VARCHAR,details_json JSON,PRIMARY KEY(backend,test_case));
"""
