"""DuckDB schema for the isolated Alpha Research Engine."""

DDL = """
CREATE TABLE IF NOT EXISTS alpha_feature_registry(feature_id VARCHAR PRIMARY KEY,name VARCHAR,family VARCHAR,description VARCHAR,source VARCHAR,formula VARCHAR,effective_from DATE,effective_to DATE,minimum_history INTEGER,frequency VARCHAR,lag_sessions INTEGER,pit_status VARCHAR,quality_status VARCHAR,observations BIGINT,missingness DOUBLE,last_date DATE,author VARCHAR,version VARCHAR,updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS alpha_feature_importance(run_id VARCHAR,feature_id VARCHAR,horizon INTEGER,fold INTEGER,ic DOUBLE,rank_ic DOUBLE,mutual_information DOUBLE,linear_shap DOUBLE,permutation_importance DOUBLE,effect_sign INTEGER,regime_sign_changes INTEGER,p_value DOUBLE,ci_low DOUBLE,ci_high DOUBLE,train_from DATE,train_to DATE,test_from DATE,test_to DATE,method VARCHAR,PRIMARY KEY(run_id,feature_id,horizon,fold));
CREATE TABLE IF NOT EXISTS alpha_discovered_regimes(run_id VARCHAR,algorithm VARCHAR,k INTEGER,regime INTEGER,date_from DATE,date_to DATE,observations BIGINT,mean_return DOUBLE,volatility DOUBLE,up_probability DOUBLE,mean_duration DOUBLE,max_drawdown DOUBLE,recovery_sessions DOUBLE,stability DOUBLE,selected BOOLEAN,details_json JSON,PRIMARY KEY(run_id,algorithm,k,regime));
CREATE TABLE IF NOT EXISTS alpha_regime_assignments(run_id VARCHAR,trade_date DATE,algorithm VARCHAR,k INTEGER,regime INTEGER,selected BOOLEAN,PRIMARY KEY(run_id,trade_date,algorithm,k));
CREATE TABLE IF NOT EXISTS alpha_regime_transitions(run_id VARCHAR,algorithm VARCHAR,k INTEGER,from_regime INTEGER,to_regime INTEGER,probability DOUBLE,observations BIGINT,PRIMARY KEY(run_id,algorithm,k,from_regime,to_regime));
CREATE TABLE IF NOT EXISTS alpha_interactions(run_id VARCHAR,horizon INTEGER,left_feature VARCHAR,right_feature VARCHAR,interaction_name VARCHAR,ic DOUBLE,incremental_ic DOUBLE,p_value DOUBLE,ci_low DOUBLE,ci_high DOUBLE,folds_positive INTEGER,folds INTEGER,status VARCHAR,PRIMARY KEY(run_id,horizon,interaction_name));
CREATE TABLE IF NOT EXISTS alpha_market_state(trade_date DATE,block VARCHAR,score DOUBLE,direction VARCHAR,contributors_json JSON,explanation VARCHAR,version VARCHAR,PRIMARY KEY(trade_date,block,version));
CREATE TABLE IF NOT EXISTS alpha_decay(run_id VARCHAR,feature_id VARCHAR,horizon INTEGER,ic DOUBLE,rank_ic DOUBLE,p_value DOUBLE,ci_low DOUBLE,ci_high DOUBLE,status VARCHAR,PRIMARY KEY(run_id,feature_id,horizon));
CREATE TABLE IF NOT EXISTS alpha_feature_stability(run_id VARCHAR,feature_id VARCHAR,horizon INTEGER,years_working DOUBLE,regimes_working INTEGER,folds_working INTEGER,folds_total INTEGER,coefficient_variation DOUBLE,importance_variation DOUBLE,sign_consistency DOUBLE,stability_score DOUBLE,status VARCHAR,PRIMARY KEY(run_id,feature_id,horizon));
CREATE TABLE IF NOT EXISTS alpha_factor_library(run_id VARCHAR,feature_id VARCHAR,horizon INTEGER,classification VARCHAR,best_ic DOUBLE,best_rank_ic DOUBLE,stability_score DOUBLE,p_value DOUBLE,observations BIGINT,reason VARCHAR,updated_at TIMESTAMP,PRIMARY KEY(run_id,feature_id,horizon));
CREATE TABLE IF NOT EXISTS alpha_explanations(as_of_date DATE,horizon INTEGER,positive_json JSON,negative_json JSON,neutral_json JSON,model VARCHAR,model_status VARCHAR,limitations_json JSON,run_id VARCHAR,PRIMARY KEY(as_of_date,horizon,run_id));
CREATE TABLE IF NOT EXISTS alpha_research_journal(run_id VARCHAR,created_at TIMESTAMP,step VARCHAR,status VARCHAR,rows_written BIGINT,summary_json JSON,methodology VARCHAR,PRIMARY KEY(run_id,step));
"""